@TicketingSystem.WebsApi_HostAddress = http://localhost:5029

@TicketingSystem.CartId = SomeValueHere;

GET {{TicketingSystem.WebsApi_HostAddress}}/venues/
Accept: application/json
###

GET {{TicketingSystem.WebsApi_HostAddress}}/purchases/
Accept: application/json

###

GET {{TicketingSystem.WebsApi_HostAddress}}/orders/{{TicketingSystem.CartId}}
Accept: application/json

###

GET {{TicketingSystem.WebsApi_HostAddress}}/events/
Accept: application/json