// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.ticketingSystem
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class MessageValue : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""MessageValue"",""namespace"":""com.ticketingSystem"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Operation"",""type"":""int""},{""name"":""Timestamp"",""default"":0,""type"":[{""type"":""long"",""logicalType"":""timestamp-millis""},""null""]},{""name"":""CustomerEmail"",""type"":""string""},{""name"":""CustomerName"",""type"":""string""},{""name"":""OrderAmount"",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":4,""scale"":2}},{""name"":""OrderSummary"",""type"":""string""}]}");
		private string _Id;
		private int _Operation;
		private System.Nullable<System.DateTime> _Timestamp;
		private string _CustomerEmail;
		private string _CustomerName;
		private Avro.AvroDecimal _OrderAmount;
		private string _OrderSummary;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return MessageValue._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public int Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				this._Operation = value;
			}
		}
		public System.Nullable<System.DateTime> Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				this._Timestamp = value;
			}
		}
		public string CustomerEmail
		{
			get
			{
				return this._CustomerEmail;
			}
			set
			{
				this._CustomerEmail = value;
			}
		}
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				this._CustomerName = value;
			}
		}
		public Avro.AvroDecimal OrderAmount
		{
			get
			{
				return this._OrderAmount;
			}
			set
			{
				this._OrderAmount = value;
			}
		}
		public string OrderSummary
		{
			get
			{
				return this._OrderSummary;
			}
			set
			{
				this._OrderSummary = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Operation;
			case 2: return this.Timestamp;
			case 3: return this.CustomerEmail;
			case 4: return this.CustomerName;
			case 5: return this.OrderAmount;
			case 6: return this.OrderSummary;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Operation = (System.Int32)fieldValue; break;
			case 2: this.Timestamp = (System.Nullable<System.DateTime>)fieldValue; break;
			case 3: this.CustomerEmail = (System.String)fieldValue; break;
			case 4: this.CustomerName = (System.String)fieldValue; break;
			case 5: this.OrderAmount = (Avro.AvroDecimal)fieldValue; break;
			case 6: this.OrderSummary = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
